apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysa
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mysa-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mysa-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mysa-role
subjects:
- kind: ServiceAccount
  name: mysa