FROM centos
ENV name Docker
ENTRYPOINT echo "hello $name"

# docker build -t peterhly/centos-entrypoint-shell .    ## 构建image
# docker run peterhly/centos-entrypoint-shell           ## 生成container并运行
